name: Sync Fork

on:
  push:
    branches:
      - main    # Triggers on push to the main branch
      - '*'     # Triggers on push to any branch
  workflow_dispatch: # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the fork repository
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.PAT }}
      
      - name: Add upstream repository
        run: git remote add upstream https://github.com/DigitalProductInnovationAndDevelopment/Security-Compliance-Assessment.git

      - name: Fetch all branches from upstream
        run: git fetch upstream

      - name: Set GitHub committer identity
        run: |
          git config --global user.email "mourabitiziyad@gmail.com"
          git config --global user.name "Ziyad Mourabiti"

      - name: Merge and push all branches
        run: |
          for branch in $(git branch -r | grep upstream | grep -v '\->'); do
            branch_name=${branch#*/} # Remove 'upstream/' prefix

            if git show-ref --verify --quiet refs/heads/$branch_name; then
              git checkout $branch_name
              git merge upstream/$branch_name --no-ff
            else
              git checkout -b $branch_name $branch
              git push origin $branch_name
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Push changes to fork
        run: git push --all
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
