name: Sync to Fork

on:
  push:
    branches:
      - '**'  # Match all branches

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_SOURCE }} # Personal Access Token for the source repo

      - name: Set up Git for committing
        run: |
          git config --global user.email "mourabitiziyad@gmail.com"
          git config --global user.name "Ziyad Mourabiti"

      - name: Add the fork repository as a remote
        run: git remote add fork https://github.com/mourabitiziyad/Security-Compliance-Assessment.git

      - name: Push changes to the fork
        run: |
          git push fork --all
          git push fork --tags
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_FORK }} # Personal Access Token for the fork repo
